In [1]:
import numpy as np
import pandas as pd
import matplotlib as plot

In [2]:
train = pd.read_csv('raw_data/train.csv')
test = pd.read_csv('raw_data/test.csv')
train_header = train.columns
test_header = test.columns
train_y = train.iloc[:, -1]
train.drop(columns=['exceeds50K'], inplace=True)

print('train headers:', train_header)
print('test headers:', test_header)

train headers: Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'sex', 'capital-gain',
       'capital-loss', 'hours-per-week', 'native-country', 'exceeds50K'],
      dtype='object')
test headers: Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'sex', 'capital-gain',
       'capital-loss', 'hours-per-week', 'native-country'],
      dtype='object')

In [3]:
"""
auto fill NaN value of train set
"""
# replace ' ?' with NaN, then can use fillna() to auto fill.
train.replace({'native-country': {' ?': np.nan}}, regex=False, inplace=True)
train.replace({'workclass': {' ?': np.nan}}, regex=False, inplace=True)
train.replace({'occupation': {' ?': np.nan}}, regex=False, inplace=True)

# auto fill workclass feature
value_count = train.workclass.value_counts()
value_count = value_count / train['workclass'].count()  # .count() only count non-NaN value
list_workclass = ['Private', 'Self-emp-not-inc', 'Local-gov', 'State-gov', 'Self-emp-inc', 'Federal-gov', 'Without-pay', 'Never-worked']
prob_workclass = list(value_count)
train['workclass'].fillna(np.random.choice(list_workclass, p=prob_workclass), inplace=True)  # np.random.choice() can random choice value in list with probability p

# auto fill occupation feature
value_count = train.occupation.value_counts()
value_count = value_count / train['occupation'].count()
list_occupation = ['Prof-specialty', 'Craft-repair', 'Exec-managerial', 'Adm-clerical', 'Sales', 'Other-service', 
                  'Machine-op-inspct', 'Transport-moving', 'Handlers-cleaners', 'Farming-fishing', 'Tech-support', 
                  'Protective-serv', 'Priv-house-serv', 'Armed-Forces']
prob_occupation = list(value_count)
train['occupation'].fillna(np.random.choice(list_occupation, p=prob_occupation), inplace=True)

# auto fill native-country feature
value_count = train.loc[:, 'native-country'].value_counts()
value_count = value_count / train['native-country'].count()
list_native_country = ['United-States', 'Mexico', 'Philippines', 'Germany', 'Puerto-Rico', 'El-Salvador', 'Canada', 
                      'India', 'Cuba', 'China', 'England', 'Italy', 'Jamaica', 'South', 'Japan', 'Poland', 'Guatemala', 
                      'Dominican-Republic', 'Columbia', 'Vietnam', 'Portugal', 'Iran', 'Haiti', 'Taiwan', 'Greece', 
                      'Nicaragua', 'Peru', 'Ecuador', 'France', 'Ireland', 'Laos', 'Thailand', 'Cambodia', 'Hong', 
                      'Yugoslavia', 'Trinadad&Tobago', 'Hondurags', 'Scotland', 'Outlying-US(Guam-USVI-etc)', 'Hungary']
prob_native_country = list(value_count)
train['native-country'].fillna(np.random.choice(list_native_country, p=prob_native_country), inplace=True)

print(train.loc[32])
print(train)

age                           55
workclass                Private
fnlwgt                    158702
education           Some-college
education-num                 10
marital-status     Never-married
occupation          Adm-clerical
relationship       Not-in-family
sex                       Female
capital-gain                   0
capital-loss                2339
hours-per-week                45
native-country     United-States
Name: 32, dtype: object
       age     workclass  fnlwgt      education  education-num  \
0       30  Self-emp-inc  147215   Some-college             10
1       60       Private  173960      Bachelors             13
2       52  Self-emp-inc  105428   Some-college             10
3       37       Private  112497      Bachelors             13
4       63       Private  137843   Some-college             10
...    ...           ...     ...            ...            ...
24416   44       Private  104196        Masters             14
24417   52       Private  112959   Some-college             10
24418   50     State-gov  263200      Assoc-voc             11
24419   25       Private  228608   Some-college             10
24420   57   Federal-gov  140711      Bachelors             13

            marital-status        occupation     relationship      sex  \
0            Never-married      Adm-clerical        Own-child   Female
1                 Divorced    Prof-specialty    Not-in-family   Female
2       Married-civ-spouse      Adm-clerical          Husband     Male
3       Married-civ-spouse             Sales          Husband     Male
4       Married-civ-spouse             Sales          Husband     Male
...                    ...               ...              ...      ...
24416   Married-civ-spouse   Exec-managerial          Husband     Male
24417              Widowed             Sales    Not-in-family   Female
24418             Divorced      Adm-clerical        Unmarried   Female
24419        Never-married      Craft-repair   Other-relative   Female
24420   Married-civ-spouse    Prof-specialty          Husband     Male

       capital-gain  capital-loss  hours-per-week  native-country
0                 0             0              30   United-States
1                 0             0              42   United-States
2                 0             0              12   United-States
3                 0             0              60   United-States
4              7298             0              48   United-States
...             ...           ...             ...             ...
24416             0             0              45   United-States
24417             0             0              40   United-States
24418             0             0              40         Ecuador
24419             0             0              40        Cambodia
24420             0             0              40   United-States

[24421 rows x 13 columns]

In [4]:
"""
auto fill NaN value of test set
"""
# replace ' ?' with NaN, then can use fillna() to auto fill.
test.replace({'native-country': {' ?': np.nan}}, regex=False, inplace=True)
test.replace({'workclass': {' ?': np.nan}}, regex=False, inplace=True)
test.replace({'occupation': {' ?': np.nan}}, regex=False, inplace=True)

# auto fill workclass feature
value_count = test.workclass.value_counts()
value_count = value_count / test['workclass'].count()  # .count() only count non-NaN value
list_workclass = ['Private', 'Self-emp-not-inc', 'Local-gov', 'State-gov', 'Self-emp-inc', 'Federal-gov', 'Without-pay', 'Never-worked']
prob_workclass = list(value_count)
test['workclass'].fillna(np.random.choice(list_workclass, p=prob_workclass), inplace=True)  # np.random.choice() can random choice value in list with probability p

# auto fill occupation feature
value_count = test.occupation.value_counts()
value_count = value_count / test['occupation'].count()
list_occupation = ['Exec-managerial', 'Craft-repair', 'Prof-specialty', 'Adm-clerical', 'Sales', 'Other-service', 
                  'Machine-op-inspct', 'Transport-moving', 'Handlers-cleaners', 'Farming-fishing', 'Tech-support', 
                  'Protective-serv', 'Priv-house-serv', 'Armed-Forces']
prob_occupation = list(value_count)
test['occupation'].fillna(np.random.choice(list_occupation, p=prob_occupation), inplace=True)

# auto fill native-country feature
test['native-country'].fillna('United-States', inplace=True)

print(test.loc[12])
print(test.loc[21])

age                           18
workclass                Private
fnlwgt                    197057
education                   10th
education-num                  6
marital-status     Never-married
occupation         Other-service
relationship           Own-child
sex                         Male
capital-gain                   0
capital-loss                   0
hours-per-week                40
native-country     United-States
Name: 12, dtype: object
age                           18
workclass           Never-worked
fnlwgt                    162908
education                   11th
education-num                  7
marital-status     Never-married
occupation         Other-service
relationship           Own-child
sex                         Male
capital-gain                   0
capital-loss                   0
hours-per-week                35
native-country     United-States
Name: 21, dtype: object

In [5]:
train = np.array(train)
test = np.array(test)
print('train rows:', train.shape[0])
print('test rows:', test.shape[0])

train rows: 24421
test rows: 24421

In [6]:
# process age
age = train[:, 0]
for i in range(len(age)):
    if age[i] >=17 and age[i] <= 20:
        age[i] = 1
    elif age[i] >= 21 and age[i] <= 30:
        age[i] = 2
    elif age[i] >= 31 and age[i] <= 40:
        age[i] = 3
    elif age[i] >= 41 and age[i] <= 50:
        age[i] = 4
    elif age[i] >= 51 and age[i] <= 60:
        age[i] = 5
    elif age[i] >= 61 and age[i] <= 70:
        age[i] = 6
    elif age[i] >= 71 and age[i] <= 80:
        age[i] = 7
    elif age[i] >= 81 and age[i] <= 90:
        age[i] = 8
print(age)

age = test[:, 0]
for i in range(len(age)):
    if age[i] >=17 and age[i] <= 20:
        age[i] = 1
    elif age[i] >= 21 and age[i] <= 30:
        age[i] = 2
    elif age[i] >= 31 and age[i] <= 40:
        age[i] = 3
    elif age[i] >= 41 and age[i] <= 50:
        age[i] = 4
    elif age[i] >= 51 and age[i] <= 60:
        age[i] = 5
    elif age[i] >= 61 and age[i] <= 70:
        age[i] = 6
    elif age[i] >= 71 and age[i] <= 80:
        age[i] = 7
    elif age[i] >= 81 and age[i] <= 90:
        age[i] = 8
print(age)

[2 5 5 ... 4 2 5]
[2 6 2 ... 3 2 4]

In [7]:
# process work class
work_class = train[:, 1]
for i in range(len(work_class)):
    if work_class[i].strip() == 'Private':
        work_class[i] = 1
    elif 'gov' in work_class[i].strip():
        work_class[i] = 2
    elif 'Self' in work_class[i]:
        work_class[i] = 3
    else:
        work_class[i] = 4

work_class_test = test[:, 1]
for j in range(len(work_class_test)):
    if 'Private' in work_class_test[j]:
        work_class_test[j] = 1
    elif 'gov' in work_class_test[j]:
        work_class_test[j] = 2
    elif 'Self' in work_class_test[j]:
        work_class_test[j] = 3
    else:
        work_class_test[j] = 4
        
work_class_extend = pd.get_dummies(work_class)
train = np.hstack([train, work_class_extend])
work_class_test_extend = pd.get_dummies(work_class_test)
test = np.hstack([test, work_class_test_extend])

In [8]:
# process marital status
marital_status = train[:, 5]
for i in range(len(marital_status)):
    if 'Married-' in marital_status[i]:
        marital_status[i] = 1
    elif 'Never-' in marital_status[i]:
        marital_status[i] = 2
    elif 'Divorced' in marital_status[i]:
        marital_status[i] = 3
    elif 'Widowed' in marital_status[i]:
        marital_status[i] = 4
    else:
        marital_status[i] = 5
print(marital_status)
marital_status_extend = pd.get_dummies(marital_status)
train = np.hstack([train, marital_status_extend])

marital_status = test[:, 5]
for i in range(len(marital_status)):
    if 'Married-' in marital_status[i]:
        marital_status[i] = 1
    elif 'Never-' in marital_status[i]:
        marital_status[i] = 2
    elif 'Divorced' in marital_status[i]:
        marital_status[i] = 3
    elif 'Widowed' in marital_status[i]:
        marital_status[i] = 4
    else:
        marital_status[i] = 5
print(marital_status)
marital_status_extend = pd.get_dummies(marital_status)
test = np.hstack([test, marital_status_extend])

[2 3 1 ... 3 2 1]
[1 4 2 ... 5 2 3]

In [9]:
# process relationship
relationship = train[:, 7]
for i in range(len(relationship)):
    if 'Own-child' in relationship[i]:
        relationship[i] = 1
    elif 'Wife' in relationship[i]:
        relationship[i] = 2
    elif 'Husband' in relationship[i]:
        relationship[i] = 3
    elif 'Not-in-family' in relationship[i]:
        relationship[i] = 4
    elif 'Other-relative' in relationship[i]:
        relationship[i] = 5
    else:
        relationship[i] = 6
print(relationship)
relationship_extend = pd.get_dummies(relationship)
train = np.hstack([train, relationship_extend])

relationship = test[:, 7]
for i in range(len(relationship)):
    if 'Own-child' in relationship[i]:
        relationship[i] = 1
    elif 'Wife' in relationship[i]:
        relationship[i] = 2
    elif 'Husband' in relationship[i]:
        relationship[i] = 3
    elif 'Not-in-family' in relationship[i]:
        relationship[i] = 4
    elif 'Other-relative' in relationship[i]:
        relationship[i] = 5
    else:
        relationship[i] = 6
print(relationship)
relationship_extend = pd.get_dummies(relationship)
test = np.hstack([test, relationship_extend])

[1 4 3 ... 6 5 3]
[3 6 4 ... 6 4 6]

In [10]:
# process sex
sex = train[:, 8]
for i in range(len(sex)):
    if 'Female' in sex[i]:
        sex[i] = 1
    else:
        sex[i] = 2
print(sex)

sex = test[:, 8]
for i in range(len(sex)):
    if 'Female' in sex[i]:
        sex[i] = 1
    else:
        sex[i] = 2
print(sex)

[1 1 2 ... 1 1 2]
[2 2 1 ... 1 1 2]

In [11]:
# process hours per week
hours_per_week = train[:, 11]
for i in range(len(hours_per_week)):
    if hours_per_week[i] < 35:
        hours_per_week[i] = 1
    elif hours_per_week[i] >= 35 and hours_per_week[i] <= 45:
        hours_per_week[i] = 2
    elif hours_per_week[i] > 45:
        hours_per_week[i] = 3
print(hours_per_week)

hours_per_week = test[:, 11]
for i in range(len(hours_per_week)):
    if hours_per_week[i] < 35:
        hours_per_week[i] = 1
    elif hours_per_week[i] >= 35 and hours_per_week[i] <= 45:
        hours_per_week[i] = 2
    elif hours_per_week[i] > 45:
        hours_per_week[i] = 3
print(hours_per_week)

[1 2 1 ... 2 2 2]
[1 2 2 ... 2 2 3]

In [12]:
# process occupation
occupation = train[:, 6]
for i in range(len(occupation)):
    if 'Tech-support' in occupation[i]:
        occupation[i] = 1
    elif 'Craft-repair' in occupation[i]:
        occupation[i] = 2
    elif 'Other-service' in occupation[i]:
        occupation[i] = 3
    elif 'Sales' in occupation[i]:
        occupation[i] = 4
    elif 'Exec-managerial' in occupation[i]:
        occupation[i] = 5
    elif 'Prof-specialty' in occupation[i]:
        occupation[i] = 6
    elif 'Handlers-cleaners' in occupation[i]:
        occupation[i] = 7
    elif 'Machine-op-inspct' in occupation[i]:
        occupation[i] = 8
    elif 'Adm-clerical' in occupation[i]:
        occupation[i] = 9
    elif 'Farming-fishing' in occupation[i]:
        occupation[i] = 10
    elif 'Transport-moving' in occupation[i]:
        occupation[i] = 11
    elif 'Priv-house-serv' in occupation[i]:
        occupation[i] = 12
    elif 'Protective-serv' in occupation[i]:
        occupation[i] = 13
    elif 'Armed-Forces' in occupation[i]:
        occupation[i] = 14
print(occupation)
occupation_extend = pd.get_dummies(occupation)
train = np.hstack([train, occupation_extend])

occupation = test[:, 6]
for i in range(len(occupation)):
    if 'Tech-support' in occupation[i]:
        occupation[i] = 1
    elif 'Craft-repair' in occupation[i]:
        occupation[i] = 2
    elif 'Other-service' in occupation[i]:
        occupation[i] = 3
    elif 'Sales' in occupation[i]:
        occupation[i] = 4
    elif 'Exec-managerial' in occupation[i]:
        occupation[i] = 5
    elif 'Prof-specialty' in occupation[i]:
        occupation[i] = 6
    elif 'Handlers-cleaners' in occupation[i]:
        occupation[i] = 7
    elif 'Machine-op-inspct' in occupation[i]:
        occupation[i] = 8
    elif 'Adm-clerical' in occupation[i]:
        occupation[i] = 9
    elif 'Farming-fishing' in occupation[i]:
        occupation[i] = 10
    elif 'Transport-moving' in occupation[i]:
        occupation[i] = 11
    elif 'Priv-house-serv' in occupation[i]:
        occupation[i] = 12
    elif 'Protective-serv' in occupation[i]:
        occupation[i] = 13
    elif 'Armed-Forces' in occupation[i]:
        occupation[i] = 14
print(occupation)
occupation_extend = pd.get_dummies(occupation)
test = np.hstack([test, occupation_extend])

[9 6 9 ... 9 2 6]
[4 8 4 ... 9 2 4]

In [13]:
df_train = pd.DataFrame(data=train)
print(df_train)
df_test = pd.DataFrame(data=test)
print(df_test)

      0  1       2              3   4  5  6  7  8     9   ... 32 33 34 35 36  \
0      2  3  147215   Some-college  10  2  9  1  1     0  ...  0  0  0  0  1
1      5  1  173960      Bachelors  13  3  6  4  1     0  ...  0  1  0  0  0
2      5  3  105428   Some-college  10  1  9  3  2     0  ...  0  0  0  0  1
3      3  1  112497      Bachelors  13  1  4  3  2     0  ...  0  0  0  0  0
4      6  1  137843   Some-college  10  1  4  3  2  7298  ...  0  0  0  0  0
...   .. ..     ...            ...  .. .. .. .. ..   ...  ... .. .. .. .. ..
24416  4  1  104196        Masters  14  1  5  3  2     0  ...  1  0  0  0  0
24417  5  1  112959   Some-college  10  4  4  4  1     0  ...  0  0  0  0  0
24418  4  2  263200      Assoc-voc  11  3  9  6  1     0  ...  0  0  0  0  1
24419  2  1  228608   Some-college  10  2  2  5  1     0  ...  0  0  0  0  0
24420  5  2  140711      Bachelors  13  1  6  3  2     0  ...  0  1  0  0  0

      37 38 39 40 41
0      0  0  0  0  0
1      0  0  0  0  0
2      0  0  0  0  0
3      0  0  0  0  0
4      0  0  0  0  0
...   .. .. .. .. ..
24416  0  0  0  0  0
24417  0  0  0  0  0
24418  0  0  0  0  0
24419  0  0  0  0  0
24420  0  0  0  0  0

[24421 rows x 42 columns]
      0  1       2              3   4  5   6  7  8     9   ... 32 33 34 35 36  \
0      2  1   32732   Some-college  10  1   4  3  2     0  ...  0  0  0  0  0
1      6  1  165017        HS-grad   9  4   8  6  2  2538  ...  0  0  0  1  0
2      2  1   36440      Bachelors  13  2   4  4  1     0  ...  0  0  0  0  0
3      3  1  182217   Some-college  10  1   3  2  1     0  ...  0  0  0  0  0
4      2  1   89347           11th   7  2   8  4  1     0  ...  0  0  0  1  0
...   .. ..     ...            ...  .. ..  .. .. ..   ...  ... .. .. .. .. ..
24416  2  1  109186   Some-college  10  1   4  3  2     0  ...  0  0  0  0  0
24417  5  1  254680        HS-grad   9  1  11  3  2     0  ...  0  0  0  0  0
24418  3  1  116218   Some-college  10  5   9  6  1     0  ...  0  0  0  0  1
24419  2  1  253262   Some-college  10  2   2  4  1     0  ...  0  0  0  0  0
24420  4  1  177536   Some-college  10  3   4  6  2     0  ...  0  0  0  0  0

      37 38 39 40 41
0      0  0  0  0  0
1      0  0  0  0  0
2      0  0  0  0  0
3      0  0  0  0  0
4      0  0  0  0  0
...   .. .. .. .. ..
24416  0  0  0  0  0
24417  0  1  0  0  0
24418  0  0  0  0  0
24419  0  0  0  0  0
24420  0  0  0  0  0

[24421 rows x 42 columns]

In [14]:
# drop some useless features
# df_train.drop(columns=['fnlwgt', 'education', 'capital-gain', 'capital-loss', 'native-country', 
#                        'workclass', 'marital-status', 'relationship'], inplace=True)
df_train.drop(columns=[1, 2, 3, 5, 7, 9, 10, 12], inplace=True)
print(df_train)
# df_test.drop(columns=['fnlwgt', 'education', 'capital-gain', 'capital-loss', 'native-country', 
#                       'workclass', 'marital-status', 'relationship'], inplace=True)
df_test.drop(columns=[1, 2, 3, 5, 7, 9, 10, 12], inplace=True)
print(df_test)

      0   4  6  8  11 13 14 15 16 17  ... 32 33 34 35 36 37 38 39 40 41
0      2  10  9  1  1  0  0  1  0  0  ...  0  0  0  0  1  0  0  0  0  0
1      5  13  6  1  2  1  0  0  0  0  ...  0  1  0  0  0  0  0  0  0  0
2      5  10  9  2  1  0  0  1  0  1  ...  0  0  0  0  1  0  0  0  0  0
3      3  13  4  2  3  1  0  0  0  1  ...  0  0  0  0  0  0  0  0  0  0
4      6  10  4  2  3  1  0  0  0  1  ...  0  0  0  0  0  0  0  0  0  0
...   ..  .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
24416  4  14  5  2  2  1  0  0  0  1  ...  1  0  0  0  0  0  0  0  0  0
24417  5  10  4  1  2  1  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
24418  4  11  9  1  2  0  1  0  0  0  ...  0  0  0  0  1  0  0  0  0  0
24419  2  10  2  1  2  1  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
24420  5  13  6  2  2  0  1  0  0  1  ...  0  1  0  0  0  0  0  0  0  0

[24421 rows x 34 columns]
      0   4   6  8  11 13 14 15 16 17  ... 32 33 34 35 36 37 38 39 40 41
0      2  10   4  2  1  1  0  0  0  1  ...  0  0  0  0  0  0  0  0  0  0
1      6   9   8  2  2  1  0  0  0  0  ...  0  0  0  1  0  0  0  0  0  0
2      2  13   4  1  2  1  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
3      3  10   3  1  2  1  0  0  0  1  ...  0  0  0  0  0  0  0  0  0  0
4      2   7   8  1  2  1  0  0  0  0  ...  0  0  0  1  0  0  0  0  0  0
...   ..  ..  .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
24416  2  10   4  2  3  1  0  0  0  1  ...  0  0  0  0  0  0  0  0  0  0
24417  5   9  11  2  3  1  0  0  0  1  ...  0  0  0  0  0  0  1  0  0  0
24418  3  10   9  1  2  1  0  0  0  0  ...  0  0  0  0  1  0  0  0  0  0
24419  2  10   2  1  2  1  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
24420  4  10   4  2  3  1  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0

[24421 rows x 34 columns]

In [15]:
df_train = pd.concat([df_train, train_y], axis=1)

In [16]:
# write to file
df_train.to_csv('./processed_data/train_4.csv', index=None)
df_test.to_csv('./processed_data/test_4.csv', index=None)